version: '3.8'

services:
  mysql:
    build: .
    container_name: electronics_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: electronics_shop
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/01-database.sql
      - ./data.sql:/docker-entrypoint-initdb.d/02-data.sql
      - ./triggers.sql:/docker-entrypoint-initdb.d/03-triggers.sql

  adminer:
    image: adminer
    container_name: electronics_admin
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
